### ISSUE TITLE
Analyse von Messfehlern (Aufgabe 4)

### ISSUE THREAD

**Issue by MizuLuna** [DavidTaube/Projekt2#2]
Wir überlegen momentan was Litschke genau von uns will.
Bisher haben wir uns überlegt, dass wir suchen welche Fehler tendenziell in den Logs auftreten könnten
(Verzehrung, Rundungsfehler, Warum es Bilder doppelt gibt, etc. ).
Diese dann in einer Grafik anzeigen, nachdem sie analysiert wurden.

Sehen wir die Aufgabe dann so richtig? Oder sind wir jetzt total auf dem Holzweg?
Wir wollten Litschke dann auch nochmal dazu anschreiben, was genau er da eigentlich haben wollte.

**Comment by JoProt** [comment]
Hi, ich denke das ist tendenziell der richtige Ansatz (Wobei Doppelte Bilder natürlich dadurch entsehen können, dass der Kornknecht sich innerhalb des Aufzeichnungsitervall nicht bewegt hat). Ich würde vorschlagen, dass ihr erstmal euren Ansatz verfolgt und wenn uns in den Teilaufgaben noch irgendwelche anomalien auffallen, wir euch die mitteilen und dann entscheidet Ihr, ob Ihr das noch mit analysieren wollt  ;).

VG

**Comment by DavidTaube** [comment]
Ich stimme Josef zu, schriebt sonst einfach nochmal Litschke an. Und teilt eure neuen Infos mit uns.

**Comment by MizuLuna** [comment]
> Ich stimme Josef zu, schriebt sonst einfach nochmal Litschke an. Und teilt eure neuen Infos mit uns.

War bisher auch unser Plan, wollten nur mal kurz Rücksprache halten ;)

**Comment by MizuLuna** [comment]
Hier ist mal die Antwort auf die Mail von Litschke:

Die Analyse der Fehlerverteilungen aus den Logfiles ist schon mal ein
guter Ansatz. Zusätzlich kann ich Ihnen auch noch Kamerabilder geben
/ senden, damit Sie sich einen Eindruck von Abmessungen der Marker im
Bild verschaffen können.

"tatsächliche" Werte habe ich ja auch nicht - die "Messungen"
aufgrund der Kamerabilder sind die einzigen, die ich habe - mit dem
Maßband o.ä. nachgemessen habe ich nicht.

_Wir hatten nochmal gefragt, ob das nur anhand der aktuellen LogFiles passieren soll oder halt generell an solchen LogFiles._
Naja, im neuen Programm wäre schön.... wenn es sich realisieren
lässt.

**Comment by MizuLuna** [comment]
Abschluss nach dem Gespräch mit Litschke

Wir werden nun folgendes Verfolgen und schauen wie weit wir kommen:
Wir werden aufeinanderfolgende Abstände der gleichen Tafeln über Zeit in einem Diagramm eintragen und schauen wie diese Streuen. Anhand einer Mittelung der Werte, suchen wir uns den womöglich genausten Wert und die Extremstellen zu einem Zeitpunkt.

In Rechnungen, welche Relevant für das Programm sind, die diese Werte enthalten, errechnen wir Ergebnisse mit den 3 gesuchten Werten und schließen so auf Größe von Messfehlern die in den Werten vorkommen.

Spekulationen über andere Messfehler können wir vielleicht noch einbauen.

Das werden wir dann alles irgendwie Anzeigen. Wie werden wir noch sehen.
